Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2204"

  config.vm.network "forwarded_port", guest: 22, host: 2223, id: "ssh"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
  end
end
